In [12]:
import numpy as np
arr = [(8,8),(12)]


In [6]:
c = np.array([1,2,3,4,5,6,7,8])
print(c)

[1 2 3 4 5 6 7 8]


In [8]:
#1
newc = c.reshape(4,2)
newc

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [18]:
#2
dp = range(100,200,10)
newdp = np.array([dp])
converted_dp = newdp.reshape(5,2)
converted_dp

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [33]:
#3
new = np.array([[ 1,  3,  4,  5], [ 2,  3,  4,  6], [ 2, 10, 20,  2], [ 2,  3,  4,  5], [ 2,  3,  5,  6]])
for i in new:
    print(i[2])


4
4
20
4
5


In [75]:
#4
new = np.array([[ 1,  3,  4,  5], [ 2,  3,  4,  6], [ 2, 10, 20,  2], [ 2,  3,  4,  5], [ 2,  3,  5,  6]])
checked = new.reshape(-1)
even_new = np.where(checked  %2 == 0)
print(even_new)
checked   

(array([ 2,  4,  6,  7,  8,  9, 10, 11, 12, 14, 16, 19], dtype=int64),)


array([ 1,  3,  4,  5,  2,  3,  4,  6,  2, 10, 20,  2,  2,  3,  4,  5,  2,
        3,  5,  6])

In [73]:
new = np.array([[ 1,  3,  4,  5], [ 2,  3,  4,  6], [ 2, 10, 20,  2], [ 2,  3,  4,  5], [ 2,  3,  5,  6]])
odd_new = np.where(checked2 % 2 != 1)
checked2 = new.reshape(-1)
print(odd_new)

(array([ 2,  4,  6,  7,  8,  9, 10, 11, 12, 14, 16, 19], dtype=int64),)


In [79]:
#5
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)
for i in arr:
    print(i**2)

[1 2 3 4 5 6]
1
4
9
16
25
36


In [82]:
#6
newarr = np.array_split(arr, 4)
newarr

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [63]:
#7
my_new_ = np.array([[1, 3 ,4 ,5], [2 ,3, 4 ,6], [2 ,10, 20, 2]])
for i in my_new_:
    minimum = np.amin(i, 0) 
    print(minimum)
maximum = np.amax(my_new_,1)
print(maximum)
print(minimun)

1
2
2
[ 5  6 20]
[ 5  6 20]


In [66]:
#8
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(my_new_)
print("Test a given array element-wise for finiteness :")
print(np.isfinite(my_new_))


Original array
[[ 1  3  4  5]
 [ 2  3  4  6]
 [ 2 10 20  2]]
Test a given array element-wise for finiteness :
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [67]:
#9
print(np.isnan(my_new_))

[[False False False False]
 [False False False False]
 [False False False False]]


In [68]:
#10
import numpy as np
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))
print("Checking for real number:")
print(np.isreal(a))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


In [69]:
#11
import numpy as np
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


In [70]:
#12
import numpy as np
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [71]:
#13
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [72]:
#14
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [73]:
#15
import numpy as np
x = np.random.randint(0, 11, 5)
print("Vector of length 5 filled with arbitrary integers from 0 to 10:")
print(x)

Vector of length 5 filled with arbitrary integers from 0 to 10:
[0 6 6 2 8]


In [2]:
#16
import numpy as np
m= np.arange(10,22).reshape((3, 4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [75]:
#17
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [76]:
#18
import numpy as np
nums1 = np.array([0.5, 1.5, 0.2])
nums2 = np.array([0.4999999999, 1.500000000, 0.2])
np.set_printoptions(precision=15)
print("Original arrays:")
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(nums1 == nums2)
nums1 = np.array([0.5, 1.5, 0.23])
nums2 = np.array([0.4999999999, 1.5000000001, 0.23])
print("\nOriginal arrays:")
np.set_printoptions(precision=15)
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(np.equal(nums1, nums2))


Original arrays:
[0.5 1.5 0.2]
[0.4999999999 1.5          0.2         ]

Test said two arrays are equal (element wise) or not:?
[False  True  True]

Original arrays:
[0.5  1.5  0.23]
[0.4999999999 1.5000000001 0.23        ]

Test said two arrays are equal (element wise) or not:?
[False False  True]


In [77]:
#19
import numpy as np 
np.random.seed(20) 
cbrt = np.cbrt(7)
nd1 = 200 
print(cbrt * np.random.randn(10, 4) + nd1) 

[[201.69082669736346 200.3746763082702  200.68394275021677
  195.51750123129818]
 [197.92478991563303 201.07066048488275 201.79714021459858
  198.12823310277952]
 [200.96238963339914 200.77744291067876 200.61875865227867
  199.05613893807728]
 [198.48492638364303 198.38860811141893 197.55239946005003
  200.47003620983824]
 [199.9154583876559  202.99877319355295 202.01069856971475
  200.77735483308504]
 [199.67739161408255 193.89831807071494 202.14273592752286
  202.54951299405823]
 [199.53450968631876 199.75126019761723 199.791457270905
  202.97687756587686]
 [200.24634412660365 196.0460693352411  198.3061125324022
  197.88701546225133]
 [201.7845091237894  203.94032834458278 198.21152802602944
  196.9144607143198 ]
 [201.0082480992413  197.03285103581035 200.6305276348363
  197.82590294139914]]


In [78]:
#20
import numpy as np  
nums = np.array([[[1, 5, 2, 1],
               [4, 3, 5, 6],
               [6, 3, 0, 6],
               [7, 3, 5, 0],
               [2, 3, 3, 5]],
              
              [[2, 2, 3, 1],
               [4, 0, 0, 5],
               [6, 3, 2, 1],
               [5, 1, 0, 0],               
               [0, 1, 9, 1]],
              
              [[3, 1, 4, 2],
               [4, 1, 6, 0],
               [1, 2, 0, 6],
               [8, 3, 4, 0],               
               [2, 0, 2, 8]]]) 
print("Array:")
print(nums)

Array:
[[[1 5 2 1]
  [4 3 5 6]
  [6 3 0 6]
  [7 3 5 0]
  [2 3 3 5]]

 [[2 2 3 1]
  [4 0 0 5]
  [6 3 2 1]
  [5 1 0 0]
  [0 1 9 1]]

 [[3 1 4 2]
  [4 1 6 0]
  [1 2 0 6]
  [8 3 4 0]
  [2 0 2 8]]]
